# Generated by Django 4.0.4 on 2022-06-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
